In [1]:
import glob
import pandas as pd



df_list = []
for file in glob.glob(r'C:\Users\trainor-gilhamt\Documents\Unilever NL\Retailer Raw Data\*.xlsx'):
# Tweak this to work for your actual filepaths, if needed.
    FN, Retailer = file.split('.')[0].split('-')[1:]
    df = (pd.read_excel(file)

          .assign(Folder=FN, Retailer=Retailer))

    df_list.append(df)


    df = pd.concat(df_list)

In [2]:
df

,UPC,Prod Desc,Facts,2020-08-16 00:00:00,2020-08-23 00:00:00,2020-08-30 00:00:00,2020-09-06 00:00:00,2020-09-13 00:00:00,2020-09-20 00:00:00,2020-09-27 00:00:00,...,2022-07-03 00:00:00,2022-07-10 00:00:00,2022-07-17 00:00:00,2022-07-24 00:00:00,2022-07-31 00:00:00,2022-08-07 00:00:00,2022-08-14 00:00:00,2022-08-21 00:00:00,Folder,Retailer
0,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,0.174944,0.270698,0.218432,0.147533,0.22774,0.212124,0.17058,...,2.996267,2.743483,3.215072,2.588950,4.417883,5.548289,8.076058,8.336302,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Albert_Heijn
1,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Value (in EUR),17.980000,17.980000,8.990000,NaN,8.99000,35.959999,26.32000,...,71.919998,98.820000,53.939999,44.949997,134.849991,143.449997,206.769989,179.799988,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Albert_Heijn
2,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Units,2.000000,2.000000,1.000000,NaN,1.00000,4.000000,3.00000,...,8.000000,11.000000,6.000000,5.000000,15.000000,16.000000,23.000000,20.000000,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Albert_Heijn
3,8720256109433,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,0.174944,0.270698,0.218432,0.147533,0.22774,0.212124,0.17058,...,1.623789,1.339554,1.653290,2.006714,2.197398,2.083508,2.306905,1.949458,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Albert_Heijn
4,8720256109433,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Value (in EUR),8.990000,44.950001,NaN,NaN,17.98000,NaN,NaN,...,53.849998,32.809998,62.930000,70.589996,71.919998,35.959999,53.939999,62.930000,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Albert_Heijn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2053,5060120164049,TREA ARGN_L ARGAN_O WTH_MRCCN 50 ML X1,Value (in EUR),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Plus
2054,5060120164049,TREA ARGN_L ARGAN_O WTH_MRCCN 50 ML X1,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Plus
2055,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Weight. Distr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Plus
2056,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Value (in EUR),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Plus
2057,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F,Plus

In [3]:
col_name="Retailer"
first_col = df.pop(col_name)

df.insert(0, col_name, first_col)

df

,Retailer,UPC,Prod Desc,Facts,2020-08-16 00:00:00,2020-08-23 00:00:00,2020-08-30 00:00:00,2020-09-06 00:00:00,2020-09-13 00:00:00,2020-09-20 00:00:00,...,2022-06-26 00:00:00,2022-07-03 00:00:00,2022-07-10 00:00:00,2022-07-17 00:00:00,2022-07-24 00:00:00,2022-07-31 00:00:00,2022-08-07 00:00:00,2022-08-14 00:00:00,2022-08-21 00:00:00,Folder
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,0.174944,0.270698,0.218432,0.147533,0.22774,0.212124,...,2.758977,2.996267,2.743483,3.215072,2.588950,4.417883,5.548289,8.076058,8.336302,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Value (in EUR),17.980000,17.980000,8.990000,NaN,8.99000,35.959999,...,107.879997,71.919998,98.820000,53.939999,44.949997,134.849991,143.449997,206.769989,179.799988,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Units,2.000000,2.000000,1.000000,NaN,1.00000,4.000000,...,12.000000,8.000000,11.000000,6.000000,5.000000,15.000000,16.000000,23.000000,20.000000,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
3,Albert_Heijn,8720256109433,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,0.174944,0.270698,0.218432,0.147533,0.22774,0.212124,...,1.854477,1.623789,1.339554,1.653290,2.006714,2.197398,2.083508,2.306905,1.949458,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
4,Albert_Heijn,8720256109433,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Value (in EUR),8.990000,44.950001,NaN,NaN,17.98000,NaN,...,17.980000,53.849998,32.809998,62.930000,70.589996,71.919998,35.959999,53.939999,62.930000,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2053,Plus,5060120164049,TREA ARGN_L ARGAN_O WTH_MRCCN 50 ML X1,Value (in EUR),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2054,Plus,5060120164049,TREA ARGN_L ARGAN_O WTH_MRCCN 50 ML X1,Units,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2055,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Weight. Distr.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2056,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Value (in EUR),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2057,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F

In [4]:
Columns = ['Prod Desc', 'UPC']
df.loc[:,Columns] = df.loc[:,Columns].ffill()
df

,Retailer,UPC,Prod Desc,Facts,2020-08-16 00:00:00,2020-08-23 00:00:00,2020-08-30 00:00:00,2020-09-06 00:00:00,2020-09-13 00:00:00,2020-09-20 00:00:00,...,2022-06-26 00:00:00,2022-07-03 00:00:00,2022-07-10 00:00:00,2022-07-17 00:00:00,2022-07-24 00:00:00,2022-07-31 00:00:00,2022-08-07 00:00:00,2022-08-14 00:00:00,2022-08-21 00:00:00,Folder
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,0.174944,0.270698,0.218432,0.147533,0.22774,0.212124,...,2.758977,2.996267,2.743483,3.215072,2.588950,4.417883,5.548289,8.076058,8.336302,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Value (in EUR),17.980000,17.980000,8.990000,NaN,8.99000,35.959999,...,107.879997,71.919998,98.820000,53.939999,44.949997,134.849991,143.449997,206.769989,179.799988,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Units,2.000000,2.000000,1.000000,NaN,1.00000,4.000000,...,12.000000,8.000000,11.000000,6.000000,5.000000,15.000000,16.000000,23.000000,20.000000,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
3,Albert_Heijn,8720256109433,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,0.174944,0.270698,0.218432,0.147533,0.22774,0.212124,...,1.854477,1.623789,1.339554,1.653290,2.006714,2.197398,2.083508,2.306905,1.949458,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
4,Albert_Heijn,8720256109433,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Value (in EUR),8.990000,44.950001,NaN,NaN,17.98000,NaN,...,17.980000,53.849998,32.809998,62.930000,70.589996,71.919998,35.959999,53.939999,62.930000,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2053,Plus,5060120164049,TREA ARGN_L ARGAN_O WTH_MRCCN 50 ML X1,Value (in EUR),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2054,Plus,5060120164049,TREA ARGN_L ARGAN_O WTH_MRCCN 50 ML X1,Units,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2055,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Weight. Distr.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2056,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Value (in EUR),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F
2057,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gilhamt\Documents\Unilever NL\Retailer Raw Data\F

In [5]:
df2 = df.drop(columns=['Folder'])

In [6]:
Raw_Long = df2.set_index([('Retailer'),
            ('UPC'),
            ('Prod Desc'),
            ('Facts'),

            ]).stack(dropna=False).reset_index().rename(columns = {'level_4': 'Date' , 0: 'Data'})
         
Raw_Long

,Retailer,UPC,Prod Desc,Facts,Date,Data
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,2020-08-16,0.174944
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,2020-08-23,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,2020-08-30,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,2020-09-06,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,Weight. Distr.,2020-09-13,0.227740
...,...,...,...,...,...,...
1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,2022-07-24,NaN
1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,2022-07-31,NaN
1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,2022-08-07,NaN
1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,2022-08-14,NaN
1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,Units,2022-08-21,NaN

In [7]:

Raw_Long['Date'] = pd.to_datetime(Raw_Long['Date'])

In [8]:
dataTypeSeries = Raw_Long.dtypes
print(dataTypeSeries)

Retailer             object
UPC                   int64
Prod Desc            object
Facts                object
Date         datetime64[ns]
Data                float64
dtype: object

In [9]:
# Raw_Long.set_index(['Retailer', 'UPC', 'Prod Desc', 'Date'], append=True)

In [10]:
import numpy as np
 
Raw_Long['Index'] = np.arange(len(Raw_Long))
print (Raw_Long)

             Retailer            UPC  \
0        Albert_Heijn  8720256109396
1        Albert_Heijn  8720256109396
2        Albert_Heijn  8720256109396
3        Albert_Heijn  8720256109396
4        Albert_Heijn  8720256109396
...               ...            ...
1802737          Plus  5060120163714
1802738          Plus  5060120163714
1802739          Plus  5060120163714
1802740          Plus  5060120163714
1802741          Plus  5060120163714

                                        Prod Desc           Facts       Date  \
0        COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1  Weight. Distr. 2020-08-16
1        COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1  Weight. Distr. 2020-08-23
2        COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1  Weight. Distr. 2020-08-30
3        COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1  Weight. Distr. 2020-09-06
4        COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1  Weight. Distr. 2020-09-13
...                                           ...             ...        ...
1802737    TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1           Units 2022-07-24
1802738    TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1           Units 2022-07-31
1802739    TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1           Units 2022-08-07
1802740    TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1           Units 2022-08-14
1802741    TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1           Units 2022-08-21

             Data    Index
0        0.174944        0
1        0.270698        1
2        0.218432        2
3        0.147533        3
4        0.227740        4
...           ...      ...
1802737       NaN  1802737
1802738       NaN  1802738
1802739       NaN  1802739
1802740       NaN  1802740
1802741       NaN  1802741

[1802742 rows x 7 columns]

In [11]:
Raw_Long_2 = Raw_Long.pivot(index= ['Index', 'Retailer' , 'UPC' , 'Prod Desc' , 'Date'] , columns= 'Facts' , values='Data')

Raw_Long_2

,,,,Facts,Units,Value (in EUR),Weight. Distr.
Index,Retailer,UPC,Prod Desc,Date,,,
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-16,NaN,NaN,0.174944
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,NaN,NaN,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,NaN,NaN,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,NaN,NaN,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,NaN,NaN,0.227740
...,...,...,...,...,...,...,...
1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-24,NaN,NaN,NaN
1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-31,NaN,NaN,NaN
1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-07,NaN,NaN,NaN
1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-14,NaN,NaN,NaN
1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-21,NaN,NaN,NaN

In [12]:
Raw_Long_2.reset_index(inplace=True)
Raw_Long_2

Facts,Index,Retailer,UPC,Prod Desc,Date,Units,Value (in EUR),Weight. Distr.
0,0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-16,NaN,NaN,0.174944
1,1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,NaN,NaN,0.270698
2,2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,NaN,NaN,0.218432
3,3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,NaN,NaN,0.147533
4,4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,NaN,NaN,0.227740
...,...,...,...,...,...,...,...,...
1802737,1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-24,NaN,NaN,NaN
1802738,1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-31,NaN,NaN,NaN
1802739,1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-07,NaN,NaN,NaN
1802740,1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-14,NaN,NaN,NaN
1802741,1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-21,NaN,NaN,NaN

In [13]:
Final = Raw_Long_2.drop(columns=['Index'])
Final

Facts,Retailer,UPC,Prod Desc,Date,Units,Value (in EUR),Weight. Distr.
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-16,NaN,NaN,0.174944
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,NaN,NaN,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,NaN,NaN,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,NaN,NaN,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,NaN,NaN,0.227740
...,...,...,...,...,...,...,...
1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-24,NaN,NaN,NaN
1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-31,NaN,NaN,NaN
1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-07,NaN,NaN,NaN
1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-14,NaN,NaN,NaN
1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-21,NaN,NaN,NaN

In [14]:
Final.fillna(0, inplace = True)
Final

Facts,Retailer,UPC,Prod Desc,Date,Units,Value (in EUR),Weight. Distr.
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-16,0.0,0.0,0.174944
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,0.0,0.0,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,0.0,0.0,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,0.0,0.0,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,0.0,0.0,0.227740
...,...,...,...,...,...,...,...
1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-24,0.0,0.0,0.000000
1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-31,0.0,0.0,0.000000
1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-07,0.0,0.0,0.000000
1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-14,0.0,0.0,0.000000
1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-21,0.0,0.0,0.000000

In [15]:
Final2 = Final.rename(columns={'Retailer':'RETAILER','UPC':'UPC_DESC','Prod Desc':'UPC_SHORT_DESC', 'Date':'WEEK', 
                                   'Units':'UNITS', 'Value (in EUR)':'SALES (EUR)', 'Weight. Distr.':'ACV'})
Final2

Facts,RETAILER,UPC_DESC,UPC_SHORT_DESC,WEEK,UNITS,SALES (EUR),ACV
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-16,0.0,0.0,0.174944
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,0.0,0.0,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,0.0,0.0,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,0.0,0.0,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,0.0,0.0,0.227740
...,...,...,...,...,...,...,...
1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-24,0.0,0.0,0.000000
1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-31,0.0,0.0,0.000000
1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-07,0.0,0.0,0.000000
1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-14,0.0,0.0,0.000000
1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-21,0.0,0.0,0.000000

In [16]:
# groupby UPC, Retailer, UPC_DESC, 
# Choose max ACV

Final2a = Final2.groupby(['RETAILER' , 'UPC_DESC' , 'UPC_SHORT_DESC' , 'WEEK']).agg({ 'UNITS':['sum'] , 'SALES (EUR)': ['sum'] , 'ACV':['sum']})
Final2a

Facts                                                                            UNITS  \
                                                                                   sum
RETAILER     UPC_DESC      UPC_SHORT_DESC                             WEEK
Albert_Heijn 40726359      TREA GUHL RIJKE_V MN_L 200 M X1            2020-08-16  11.0
                                                                      2020-08-23  10.0
                                                                      2020-08-30  26.0
                                                                      2020-09-06  25.0
                                                                      2020-09-13  24.0
...                                                                                ...
Plus         8720572973411 BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1 2022-07-24   0.0
                                                                      2022-07-31   0.0
                                                                      2022-08-07   0.0
                                                                      2022-08-14   0.0
                                                                      2022-08-21   0.0

Facts                                                                            SALES (EUR)  \
                                                                                         sum
RETAILER     UPC_DESC      UPC_SHORT_DESC                             WEEK
Albert_Heijn 40726359      TREA GUHL RIJKE_V MN_L 200 M X1            2020-08-16  105.900002
                                                                      2020-08-23   89.190002
                                                                      2020-08-30  258.309998
                                                                      2020-09-06  252.250000
                                                                      2020-09-13  231.540009
...                                                                                      ...
Plus         8720572973411 BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1 2022-07-24    0.000000
                                                                      2022-07-31    0.000000
                                                                      2022-08-07    0.000000
                                                                      2022-08-14    0.000000
                                                                      2022-08-21    0.000000

Facts                                                                                   ACV
                                                                                        sum
RETAILER     UPC_DESC      UPC_SHORT_DESC                             WEEK
Albert_Heijn 40726359      TREA GUHL RIJKE_V MN_L 200 M X1            2020-08-16  23.468048
                                                                      2020-08-23   7.060252
                                                                      2020-08-30   9.015503
                                                                      2020-09-06  10.480256
                                                                      2020-09-13  11.215165
...                                                                                     ...
Plus         8720572973411 BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1 2022-07-24   0.000000
                                                                      2022-07-31   0.000000
                                                                      2022-08-07   0.000000
                                                                      2022-08-14   0.000000
                                                                      2022-08-21   0.000000

[564662 rows x 3 columns]

In [17]:
Final2a.reset_index(inplace=True)
Final2a

Facts,RETAILER,UPC_DESC,UPC_SHORT_DESC,WEEK,UNITS,SALES (EUR),ACV
,,,,,sum,sum,sum
0,Albert_Heijn,40726359,TREA GUHL RIJKE_V MN_L 200 M X1,2020-08-16,11.0,105.900002,23.468048
1,Albert_Heijn,40726359,TREA GUHL RIJKE_V MN_L 200 M X1,2020-08-23,10.0,89.190002,7.060252
2,Albert_Heijn,40726359,TREA GUHL RIJKE_V MN_L 200 M X1,2020-08-30,26.0,258.309998,9.015503
3,Albert_Heijn,40726359,TREA GUHL RIJKE_V MN_L 200 M X1,2020-09-06,25.0,252.250000,10.480256
4,Albert_Heijn,40726359,TREA GUHL RIJKE_V MN_L 200 M X1,2020-09-13,24.0,231.540009,11.215165
...,...,...,...,...,...,...,...
564657,Plus,8720572973411,BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1,2022-07-24,0.0,0.000000,0.000000
564658,Plus,8720572973411,BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1,2022-07-31,0.0,0.000000,0.000000
564659,Plus,8720572973411,BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1,2022-08-07,0.0,0.000000,0.000000
564660,Plus,8720572973411,BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1,2022-08-14,0.0,0.000000,0.000000
564661,Plus,8720572973411,BP1 SHAM HAPPY_SP YOU_MAK SHMP_BR ALL O X1,2022-08-21,0.0,0.000000,0.000000

In [18]:
Final3 = Final2.rename(columns={'UNITSsum':'UNITS', 'SALES (GBP)sum':'SALES (GBP)', 'ACVsum':'ACV'})
Final3

Facts,RETAILER,UPC_DESC,UPC_SHORT_DESC,WEEK,UNITS,SALES (EUR),ACV
0,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-16,0.0,0.0,0.174944
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,0.0,0.0,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,0.0,0.0,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,0.0,0.0,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,0.0,0.0,0.227740
...,...,...,...,...,...,...,...
1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-24,0.0,0.0,0.000000
1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-31,0.0,0.0,0.000000
1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-07,0.0,0.0,0.000000
1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-14,0.0,0.0,0.000000
1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-21,0.0,0.0,0.000000

In [19]:
Final3b = Final3.loc[(Final3['WEEK'] >= '2020-08-23') & (Final3['WEEK'] <= '2022-08-21' )]
Final3b

Facts,RETAILER,UPC_DESC,UPC_SHORT_DESC,WEEK,UNITS,SALES (EUR),ACV
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,0.0,0.0,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,0.0,0.0,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,0.0,0.0,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,0.0,0.0,0.227740
5,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-20,0.0,0.0,0.212124
...,...,...,...,...,...,...,...
1802737,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-24,0.0,0.0,0.000000
1802738,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-07-31,0.0,0.0,0.000000
1802739,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-07,0.0,0.0,0.000000
1802740,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-14,0.0,0.0,0.000000
1802741,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2022-08-21,0.0,0.0,0.000000

In [20]:
dataTypeSeries = Final3b.dtypes
print(dataTypeSeries)

Facts
RETAILER                  object
UPC_DESC                   int64
UPC_SHORT_DESC            object
WEEK              datetime64[ns]
UNITS                    float64
SALES (EUR)              float64
ACV                      float64
dtype: object

In [21]:
a = Final3b[(Final3b['UNITS']!=0) | (Final3b['SALES (EUR)']!=0) | (Final3b['ACV']!=0)]

In [22]:
a

Facts,RETAILER,UPC_DESC,UPC_SHORT_DESC,WEEK,UNITS,SALES (EUR),ACV
1,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-23,0.0,0.00,0.270698
2,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-08-30,0.0,0.00,0.218432
3,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-06,0.0,0.00,0.147533
4,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-13,0.0,0.00,0.227740
5,Albert_Heijn,8720256109396,COND HAPPY_SP HAPPY_S CNDTNR_BR 65 GR X1,2020-09-20,0.0,0.00,0.212124
...,...,...,...,...,...,...,...
1802457,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2021-04-04,0.0,0.00,0.431277
1802559,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2021-03-07,0.0,5.99,0.000000
1802560,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2021-03-14,0.0,5.99,0.000000
1802665,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2021-03-07,1.0,0.00,0.000000
1802666,Plus,5060120163714,TREA ARGN_L ARGAN_O WTH_MRCCN 25 ML X1,2021-03-14,1.0,0.00,0.000000

In [49]:
df_1 = a.iloc[:600000,:]
df_2 = a.iloc[600000:,:]
print("Shape of new dataframes - {} , {}".format(df_1.shape, df_2.shape))

Shape of new dataframes - (600000, 7) , (553279, 7)

In [51]:
df_1.to_csv(r'C:\Users\trainor-gilhamt\Documents\Unilever NL\Retailer Raw Data\UL_NL_Shampoos_Curve_Model_Data_Transformed_V3_1.csv', index=False)
df_2.to_csv(r'C:\Users\trainor-gilhamt\Documents\Unilever NL\Retailer Raw Data\UL_NL_Shampoos_Curve_Model_Data_Transformed_V3_2.csv', index=False)

In [23]:
a.to_csv(r'C:\Users\trainor-gilhamt\Documents\Unilever NL\Retailer Raw Data\UL_NL_Shampoos_Curve_Model_Data_Transformed_V4.csv', index=False)

In [24]:
a.to_excel(r'C:\Users\trainor-gilhamt\Documents\Unilever NL\Retailer Raw Data\UL_NL_Shampoos_Curve_Model_Data_Transformed_V4.xlsx', index=False)